import Bank from "@/types/bank";
import { RichDropdownValues } from "@/types/dropdown";

export const BANK_VALUES = [
  "abbey", "aegon", "al-rayan", "aldermore", "alliance-and-leicester", "allica", "allied-irish", "anglo-irish", "arbuthnot-latham", "atom", "aviva", "axa", "bank-of-ireland-uk", "bank-of-scotland", "barclays", "birmingham-midshires", "birmingham", "blme", "bny-mellon", "bradford-and-bingley", "brewin-dolphin", "brown-shipley", "cahoot", "castle-trust", "cater-allen", "charity", "charter-savings", "chase", "cheltenham-and-gloucester", "chip", "circa5000", "close-brothers", "cmc", "coop-bank", "coop-insurance-society", "coutts", "credit-suisse", "cynergy", "danske", "egg", "first-direct", "ford", "foresters-friendly", "freetrade", "habib-zurich", "halifax", "hampshire-trust", "handelsbanken", "hargreaves-lansdown", "healthy-investment", "hodge", "hoist", "hsbc", "icesave", "ing-direct", "intelligent-finance", "investec", "investengine", "jamaica-national", "kent-reliance", "kroo", "lhv", "lic-india", "lightyear", "lloyds-tsb", "lloyds", "london-victoria", "lloyds", "marcus", "marks-and-spencers", "mbna", "metlife", "metro", "moneybox", "moneyfarm", "monument", "monzo", "national-savings-and-investments", "nationwide", "natwest", "nfu-mutual", "northern-rock", "northern", "nutmeg", "oak-north", "octopus-investments", "one-family", "oxbury", "paragon", "phoenix-life", "plum", "post-office", "prosper", "punjab-national", "qib", "quilter", "raisin", "rbc-brewin-dolphin", "rbs", "rci", "royal-london", "saga", "sainsburys", "santander", "schroders", "scottish-friendly", "secure-trust", "shawbrook", "shepherds-friendly", "skandia", "societe-generale", "standard-life", "starling", "state-bank-of-india", "stratiphy", "strowz", "tesco", "trading-212", "transport-friendly", "triodos", "tsb", "united-national", "united-trust", "ulster", "vanguard", "vanquis", "vida", "virgin", "wealthify", "wealthtime", "xtb", "zenith", "zopa"
] as const;

export type BankValues = (typeof BANK_VALUES)[number];

const banks: readonly Bank<BankValues>[] = [
  {
    id: "abbey",
    name: "Abbey National",
    iconFile: require("@/assets/images/bank-icons/abbey.svg"),
    aliases: ["abbey", "santander", "abbey road"],
  },
  {
    id: "aegon",
    name: "Aegon",
    iconFile: require("@/assets/images/bank-icons/aegon.svg"),
    aliases: [],
  },
  {
    id: "al-rayan",
    name: "Al Rayan Bank",
    iconFile: require("@/assets/images/bank-icons/al-rayan.svg"),
    aliases: ["al rayan"],
  },
  {
    id: "aldermore",
    name: "Aldermore",
    iconFile: require("@/assets/images/bank-icons/aldermore.svg"),
    aliases: ["ruffler"],
  },
  {
    id: "alliance-and-leicester",
    name: "Alliance & Leicester",
    iconFile: require("@/assets/images/bank-icons/alliance-and-leicester.svg"),
    aliases: [
      "a&l",
      "alliance + leicester",
      "alliance",
      "leicester",
      "santander",
      "girobank",
      "alliance leicester",
    ],
  },
  {
    id: "allica",
    name: "Allica",
    iconFile: require("@/assets/images/bank-icons/allica.svg"),
    aliases: ["allica", "allied irish"],
  },
  {
    id: "allied-irish",
    name: "Allied Irish Bank",
    iconFile: require("@/assets/images/bank-icons/allied-irish.svg"),
    aliases: [
      "aib",
      "irish bank",
      "allied irish",
      "first trust",
      "provincial bank of ireland",
      "royal bank of ireland",
      "munster & leinster",
      "munster + leinster",
      "belfast banking company",
    ],
  },
  {
    id: "anglo-irish",
    name: "Anglo Irish",
    iconFile: require("@/assets/images/bank-icons/anglo-irish.svg"),
    aliases: [
      "ibrc",
      "anglo",
      "irish nationwide",
      "irish bank resolution",
      "aib",
    ],
  },
  {
    id: "arbuthnot-latham",
    name: "Arbuthnot Latham",
    iconFile: require("@/assets/images/bank-icons/arbuthnot-latham.svg"),
    aliases: ["arbuthnot", "aitken hume", "hume"],
  },
  {
    id: "atom",
    name: "Atom",
    iconFile: require("@/assets/images/bank-icons/atom.svg"),
    aliases: [],
  },
  {
    id: "aviva",
    name: "Aviva",
    iconFile: require("@/assets/images/bank-icons/aviva.svg"),
    aliases: ["norwich union", "direct line", "aig"],
  },
  {
    id: "axa",
    name: "AXA",
    iconFile: require("@/assets/images/bank-icons/axa.svg"),
    aliases: ["acksa", "a x a"],
  },
  {
    id: "bank-of-ireland-uk",
    name: "Bank of Ireland",
    iconFile: require("@/assets/images/bank-icons/bank-of-ireland-uk.svg"),
    aliases: [
      "boi",
      "banc na héireann",
      "bnh",
      "bristol and west",
      "bristol & west",
      "post office",
    ],
  },
  {
    id: "bank-of-scotland",
    name: "Bank of Scotland",
    iconFile: require("@/assets/images/bank-icons/bank-of-scotland.svg"),
    aliases: ["bos", "banca na h-alba", "alba", "lloyds", "hbos"],
  },
  {
    id: "barclays",
    name: "Barclays",
    iconFile: require("@/assets/images/bank-icons/barclays.svg"),
    aliases: [
      "barclay",
      "barklays",
      "barclay's",
      "woolwich",
      "ing direct",
      "tesco",
    ],
  },
  {
    id: "birmingham-midshires",
    name: "Birmingham Midshires",
    iconFile: require("@/assets/images/bank-icons/birmingham-midshires.svg"),
    aliases: ["bm", "brum", "b mid"],
  },
  {
    id: "birmingham",
    name: "Birmingham",
    iconFile: require("@/assets/images/bank-icons/birmingham.svg"),
    aliases: ["brum"],
  },
  {
    id: "blme",
    name: "BLME",
    iconFile: require("@/assets/images/bank-icons/blme.svg"),
    aliases: ["bank of london & the middle east", "boubyan", "nomo"],
  },
  {
    id: "bny-mellon",
    name: "BNY Mellon",
    iconFile: require("@/assets/images/bank-icons/bny-mellon.svg"),
    aliases: ["bny", "bnym"],
  },
  {
    id: "bradford-and-bingley",
    name: "Bradford & Bingley",
    iconFile: require("@/assets/images/bank-icons/bradford-and-bingley.svg"),
    aliases: ["b&m", "bnm"],
  },
  {
    id: "brewin-dolphin",
    name: "Brewin Dolphin",
    iconFile: require("@/assets/images/bank-icons/brewin-dolphin.svg"),
    aliases: ["rbc", "bd"],
  },
  {
    id: "brown-shipley",
    name: "Brown Shipley",
    iconFile: require("@/assets/images/bank-icons/brown-shipley.svg"),
    aliases: ["bs"],
  },
  {
    id: "cahoot",
    name: "Cahoot",
    iconFile: require("@/assets/images/bank-icons/cahoot.svg"),
    aliases: ["santander"],
  },
  {
    id: "castle-trust",
    name: "Castle Trust",
    iconFile: require("@/assets/images/bank-icons/castle-trust.svg"),
    aliases: ["ct"],
  },
  {
    id: "cater-allen",
    name: "Cater Allen",
    iconFile: require("@/assets/images/bank-icons/cater-allen.svg"),
    aliases: ["ca", "santander"],
  },
  {
    id: "charity",
    name: "Charity",
    iconFile: require("@/assets/images/bank-icons/charity.svg"),
    aliases: ["tcb"],
  },
  {
    id: "charter-savings",
    name: "Charter Savings",
    iconFile: require("@/assets/images/bank-icons/charter-savings.svg"),
    aliases: ["cs"],
  },
  {
    id: "chase",
    name: "Chase",
    iconFile: require("@/assets/images/bank-icons/chase.svg"),
    aliases: ["jpmorgan", "jp morgan", "jpm"],
  },
  {
    id: "cheltenham-and-gloucester",
    name: "Cheltenham & Gloucester",
    iconFile: require("@/assets/images/bank-icons/cheltenham-and-gloucester.svg"),
    aliases: ["c&g", "c+g", "lloyds"],
  },
  {
    id: "chip",
    name: "Chip",
    iconFile: require("@/assets/images/bank-icons/chip.svg"),
    aliases: [],
  },
  {
    id: "circa5000",
    name: "Cira5000",
    iconFile: require("@/assets/images/bank-icons/circa5000.svg"),
    aliases: [],
  },
  {
    id: "close-brothers",
    name: "Close Brothers",
    iconFile: require("@/assets/images/bank-icons/close-brothers.svg"),
    aliases: ["cb", "close bros"],
  },
  {
    id: "cmc",
    name: "CMC",
    iconFile: require("@/assets/images/bank-icons/cmc.svg"),
    aliases: ["deal4free"],
  },
  {
    id: "coop-bank",
    name: "The cooperative",
    iconFile: require("@/assets/images/bank-icons/coop-bank.svg"),
    aliases: ["coop", "tcb"],
  },
  {
    id: "coop-insurance-society",
    name: "Co-operative Insurance Society",
    iconFile: require("@/assets/images/bank-icons/coop-insurance-society.svg"),
    aliases: ["coop", "cis"],
  },
  {
    id: "coutts",
    name: "Coutts",
    iconFile: require("@/assets/images/bank-icons/coutts.svg"),
    aliases: [],
  },
  {
    id: "credit-suisse",
    name: "Credit Suisse",
    iconFile: require("@/assets/images/bank-icons/credit-suisse.svg"),
    aliases: ["cs"],
  },
  {
    id: "cynergy",
    name: "Cynergy",
    iconFile: require("@/assets/images/bank-icons/cynergy.svg"),
    aliases: ["bank of cyprus", "boc"],
  },
  {
    id: "danske",
    name: "Danske",
    iconFile: require("@/assets/images/bank-icons/danske.svg"),
    aliases: ["national irish", "ni"],
  },
  {
    id: "egg",
    name: "Egg",
    iconFile: require("@/assets/images/bank-icons/egg.svg"),
    aliases: ["yorkshire", "ybs", "prudential", "citi", "barclays"],
  },
  {
    id: "first-direct",
    name: "First Direct",
    iconFile: require("@/assets/images/bank-icons/first-direct.svg"),
    aliases: ["fd", "hsbc"],
  },
  {
    id: "ford",
    name: "Ford Money",
    iconFile: require("@/assets/images/bank-icons/ford.svg"),
    aliases: ["fm"],
  },
  {
    id: "foresters-friendly",
    name: "Foresters Friendly",
    iconFile: require("@/assets/images/bank-icons/foresters-friendly.svg"),
    aliases: ["fd", "hsbc"],
  },
  {
    id: "freetrade",
    name: "Freetrade",
    iconFile: require("@/assets/images/bank-icons/freetrade.svg"),
    aliases: ["ft"],
  },
  {
    id: "habib-zurich",
    name: "Habib Zurich",
    iconFile: require("@/assets/images/bank-icons/habib-zurich.svg"),
    aliases: ["hbzuk", "hb", "zurich"],
  },
  {
    id: "halifax",
    name: "Halifax",
    iconFile: require("@/assets/images/bank-icons/halifax.svg"),
    aliases: [],
  },
  {
    id: "hampshire-trust",
    name: "Hampshire Trust",
    iconFile: require("@/assets/images/bank-icons/hampshire-trust.svg"),
    aliases: ["ht"],
  },
  {
    id: "handelsbanken",
    name: "Handelsbanken",
    iconFile: require("@/assets/images/bank-icons/first-direct.svg"),
    aliases: ["fd", "hsbc"],
  },
  {
    id: "hargreaves-lansdown",
    name: "Hargreaves Lansdown",
    iconFile: require("@/assets/images/bank-icons/hargreaves-lansdown.svg"),
    aliases: ["hl"],
  },
  {
    id: "healthy-investment",
    name: "Healthy Investment",
    iconFile: require("@/assets/images/bank-icons/healthy-investment.svg"),
    aliases: ["hi"],
  },
  {
    id: "hodge",
    name: "Hodge",
    iconFile: require("@/assets/images/bank-icons/hodge.svg"),
    aliases: [],
  },
  {
    id: "hoist",
    name: "Hoist",
    iconFile: require("@/assets/images/bank-icons/hoist.svg"),
    aliases: [],
  },
  {
    id: "hsbc",
    name: "HSBC",
    iconFile: require("@/assets/images/bank-icons/hsbc.svg"),
    aliases: ["滙豐", "hong kong", "shanghai"],
  },
  {
    id: "icesave",
    name: "Icesave",
    iconFile: require("@/assets/images/bank-icons/icesave.svg"),
    aliases: ["landsbanki"],
  },
  {
    id: "ing-direct",
    name: "ING Direct",
    iconFile: require("@/assets/images/bank-icons/ing-direct.svg"),
    aliases: [],
  },
  {
    id: "intelligent-finance",
    name: "Intelligent Finance",
    iconFile: require("@/assets/images/bank-icons/intelligent-finance.svg"),
    aliases: ["if"],
  },
  {
    id: "investec",
    name: "Investec",
    iconFile: require("@/assets/images/bank-icons/investec.svg"),
    aliases: [],
  },
  {
    id: "investengine",
    name: "InvestEngine",
    iconFile: require("@/assets/images/bank-icons/investengine.svg"),
    aliases: ["ie"],
  },
  {
    id: "jamaica-national",
    name: "Jamaica National",
    iconFile: require("@/assets/images/bank-icons/jamaica-national.svg"),
    aliases: ["jnb", "jn"],
  },
  {
    id: "kent-reliance",
    name: "Kent Reliance",
    iconFile: require("@/assets/images/bank-icons/kent-reliance.svg"),
    aliases: ["kr"],
  },
  {
    id: "kroo",
    name: "Kroo",
    iconFile: require("@/assets/images/bank-icons/kroo.svg"),
    aliases: [],
  },
  {
    id: "lhv",
    name: "LHV",
    iconFile: require("@/assets/images/bank-icons/lhv.svg"),
    aliases: ["lõhmus haavel viisemann"],
  },
  {
    id: "lic-india",
    name: "Life Insurance Corporation of India",
    iconFile: require("@/assets/images/bank-icons/life-insurance-corp-india.svg"),
    aliases: ["lic", "lici"],
  },
  {
    id: "lightyear",
    name: "Lightyear",
    iconFile: require("@/assets/images/bank-icons/lightyear.svg"),
    aliases: [],
  },
  {
    id: "lloyds-tsb",
    name: "Lloyds TSB",
    iconFile: require("@/assets/images/bank-icons/lloyds-tsb.svg"),
    aliases: ["ltsb"],
  },
  {
    id: "lloyds",
    name: "Lloyds",
    iconFile: require("@/assets/images/bank-icons/lloyds.svg"),
    aliases: ["tsb", "loyds", "loids"],
  },
  {
    id: "london-victoria",
    name: "LV",
    iconFile: require("@/assets/images/bank-icons/london-victoria.svg"),
    aliases: ["london victoria"],
  },
  {
    id: "lloyds",
    name: "Lloyds",
    iconFile: require("@/assets/images/bank-icons/lloyds.svg"),
    aliases: ["tsb"],
  },
  {
    id: "marcus",
    name: "Marcus",
    iconFile: require("@/assets/images/bank-icons/marcus.svg"),
    aliases: ["goldman sachs", "gs"],
  },
  {
    id: "marks-and-spencers",
    name: "M&S",
    iconFile: require("@/assets/images/bank-icons/marks-and-spencers.svg"),
    aliases: ["m-s", "marks", "spencer", "ms"],
  },
  {
    id: "mbna",
    name: "MBNA",
    iconFile: require("@/assets/images/bank-icons/mbna.svg"),
    aliases: ["maryland", "lloyds"],
  },
  {
    id: "metlife",
    name: "Metlife",
    iconFile: require("@/assets/images/bank-icons/metlife.svg"),
    aliases: [],
  },
  {
    id: "metro",
    name: "Metro",
    iconFile: require("@/assets/images/bank-icons/metro.svg"),
    aliases: [],
  },
  {
    id: "moneybox",
    name: "Moneybox",
    iconFile: require("@/assets/images/bank-icons/moneybox.svg"),
    aliases: [],
  },
  {
    id: "moneyfarm",
    name: "Moneyfarm",
    iconFile: require("@/assets/images/bank-icons/moneyfarm.svg"),
    aliases: [],
  },
  {
    id: "monument",
    name: "Monument",
    iconFile: require("@/assets/images/bank-icons/monument.svg"),
    aliases: [],
  },
  {
    id: "monzo",
    name: "Monzo",
    iconFile: require("@/assets/images/bank-icons/monzo.svg"),
    aliases: [],
  },
  {
    id: "national-savings-and-investments",
    name: "NS&I",
    iconFile: require("@/assets/images/bank-icons/national-savings-and-investments.svg"),
    aliases: ["ns-i", "nsi"],
  },
  {
    id: "nationwide",
    name: "Nationwide",
    iconFile: require("@/assets/images/bank-icons/nationwide.svg"),
    aliases: [],
  },
  {
    id: "natwest",
    name: "NatWest",
    iconFile: require("@/assets/images/bank-icons/natwest.svg"),
    aliases: ["national westminster"],
  },
  {
    id: "nfu-mutual",
    name: "NFU Mutual",
    iconFile: require("@/assets/images/bank-icons/nfu-mutual.svg"),
    aliases: ["nfum", "national farmers union"],
  },
  {
    id: "northern-rock",
    name: "Northern Rock",
    iconFile: require("@/assets/images/bank-icons/northern-rock.svg"),
    aliases: ["nr"],
  },
  {
    id: "northern",
    name: "Northern",
    iconFile: require("@/assets/images/bank-icons/northern.svg"),
    aliases: [],
  },
  {
    id: "nutmeg",
    name: "Nutmeg",
    iconFile: require("@/assets/images/bank-icons/nutmeg.svg"),
    aliases: ["jpm", "jp morgan"],
  },
  {
    id: "oak-north",
    name: "Oak North",
    iconFile: require("@/assets/images/bank-icons/oak-north.svg"),
    aliases: ["on"],
  },
  {
    id: "octopus-investments",
    name: "Octopus Investments",
    iconFile: require("@/assets/images/bank-icons/octopus-investments.svg"),
    aliases: ["oi", "octo"],
  },
  {
    id: "one-family",
    name: "One Family",
    iconFile: require("@/assets/images/bank-icons/onefamily.svg"),
    aliases: ["of"],
  },
  {
    id: "oxbury",
    name: "Oxbury",
    iconFile: require("@/assets/images/bank-icons/oxbury.svg"),
    aliases: [],
  },
  {
    id: "paragon",
    name: "Paragon",
    iconFile: require("@/assets/images/bank-icons/paragon.svg"),
    aliases: ["paragon bank"],
  },
  {
    id: "phoenix-life",
    name: "Phoenix Life",
    iconFile: require("@/assets/images/bank-icons/phoenix-life.svg"),
    aliases: ["pl"],
  },
  {
    id: "plum",
    name: "Plum",
    iconFile: require("@/assets/images/bank-icons/plum.svg"),
    aliases: [],
  },
  {
    id: "post-office",
    name: "Post Office",
    iconFile: require("@/assets/images/bank-icons/post-office.svg"),
    aliases: ["post office money"],
  },
  {
    id: "prosper",
    name: "Prosper",
    iconFile: require("@/assets/images/bank-icons/prosper.svg"),
    aliases: [],
  },
  {
    id: "punjab-national",
    name: "Punjab National",
    iconFile: require("@/assets/images/bank-icons/punjab-national.svg"),
    aliases: ["pn"],
  },
  {
    id: "qib",
    name: "QIB",
    iconFile: require("@/assets/images/bank-icons/qib.svg"),
    aliases: ["qatar islamic"],
  },
  {
    id: "quilter",
    name: "Quilter",
    iconFile: require("@/assets/images/bank-icons/quilter.svg"),
    aliases: [],
  },
  {
    id: "raisin",
    name: "Raisin",
    iconFile: require("@/assets/images/bank-icons/raisin.svg"),
    aliases: [],
  },
  {
    id: "rbc-brewin-dolphin",
    name: "RBC Brewin Dolphin",
    iconFile: require("@/assets/images/bank-icons/rbc-brewin-dolphin.svg"),
    aliases: ["rbc", "bd", "brewin"],
  },
  {
    id: "rbs",
    name: "RBS",
    iconFile: require("@/assets/images/bank-icons/rbs-ulster.svg"),
    aliases: ["royal bank of scotland"],
  },
  {
    id: "rci",
    name: "RCI",
    iconFile: require("@/assets/images/bank-icons/rci.svg"),
    aliases: ["renault", "mobilize", "nissan", "dacia"],
  },
  {
    id: "royal-london",
    name: "Royal London",
    iconFile: require("@/assets/images/bank-icons/royal-london.svg"),
    aliases: ["rl", "cis", "coop", "abbey", "santander"],
  },
  {
    id: "saga",
    name: "Saga",
    iconFile: require("@/assets/images/bank-icons/saga.svg"),
    aliases: [],
  },
  {
    id: "sainsburys",
    name: "Sainsbury's",
    iconFile: require("@/assets/images/bank-icons/sainsburys.svg"),
    aliases: ["sainsburys"],
  },
  {
    id: "santander",
    name: "Santander",
    iconFile: require("@/assets/images/bank-icons/santander.svg"),
    aliases: ["abbey national", "satander"],
  },
  {
    id: "schroders",
    name: "Schroders",
    iconFile: require("@/assets/images/bank-icons/schroders.svg"),
    aliases: [],
  },
  {
    id: "scottish-friendly",
    name: "Scottish Friendly",
    iconFile: require("@/assets/images/bank-icons/scottish-friendly.svg"),
    aliases: ["sf"],
  },
  {
    id: "secure-trust",
    name: "Secure Trust",
    iconFile: require("@/assets/images/bank-icons/secure-trust.svg"),
    aliases: ["st"],
  },
  {
    id: "shawbrook",
    name: "Shawbrook",
    iconFile: require("@/assets/images/bank-icons/shawbrook.svg"),
    aliases: ["sb"],
  },
  {
    id: "shepherds-friendly",
    name: "Shepherds Friendly",
    iconFile: require("@/assets/images/bank-icons/shepherds-friendly.svg"),
    aliases: ["sf"],
  },
  {
    id: "skandia",
    name: "Skandia",
    iconFile: require("@/assets/images/bank-icons/skandia.svg"),
    aliases: [],
  },
  {
    id: "societe-generale",
    name: "Société Générale",
    iconFile: require("@/assets/images/bank-icons/societe-generale.svg"),
    aliases: ["sg", "societe generale"],
  },
  {
    id: "standard-life",
    name: "Standard Life",
    iconFile: require("@/assets/images/bank-icons/standard-life.svg"),
    aliases: ["sl"],
  },
  {
    id: "starling",
    name: "Starling",
    iconFile: require("@/assets/images/bank-icons/starling.svg"),
    aliases: [],
  },
  {
    id: "state-bank-of-india",
    name: "SBI",
    iconFile: require("@/assets/images/bank-icons/state-bank-of-india.svg"),
    aliases: ["standard bank of india"],
  },
  {
    id: "stratiphy",
    name: "Stratiphy",
    iconFile: require("@/assets/images/bank-icons/stratiphy.svg"),
    aliases: [],
  },
  {
    id: "strowz",
    name: "Strowz",
    iconFile: require("@/assets/images/bank-icons/strowz.svg"),
    aliases: [],
  },
  {
    id: "tesco",
    name: "Tesco",
    iconFile: require("@/assets/images/bank-icons/tesco.svg"),
    aliases: [],
  },
  {
    id: "trading-212",
    name: "Trading 212",
    iconFile: require("@/assets/images/bank-icons/trading-212.svg"),
    aliases: ["t212"],
  },
  {
    id: "transport-friendly",
    name: "Transport Friendly",
    iconFile: require("@/assets/images/bank-icons/transport-friendly.svg"),
    aliases: ["tf"],
  },
  {
    id: "triodos",
    name: "Triodos",
    iconFile: require("@/assets/images/bank-icons/triodos.svg"),
    aliases: [],
  },
  {
    id: "tsb",
    name: "TSB",
    iconFile: require("@/assets/images/bank-icons/tsb.svg"),
    aliases: ["trustee savings bank"],
  },
  {
    id: "united-national",
    name: "United National",
    iconFile: require("@/assets/images/bank-icons/united-national.svg"),
    aliases: ["un"],
  },
  {
    id: "united-trust",
    name: "United Trust",
    iconFile: require("@/assets/images/bank-icons/united-trust.svg"),
    aliases: ["ut"],
  },
  {
    id: "ulster",
    name: "Ulster",
    iconFile: require("@/assets/images/bank-icons/rbs-ulster.svg"),
    aliases: [],
  },
  {
    id: "vanguard",
    name: "Vanguard",
    iconFile: require("@/assets/images/bank-icons/vanguard.svg"),
    aliases: ["vg"],
  },
  {
    id: "vanquis",
    name: "Vanquis",
    iconFile: require("@/assets/images/bank-icons/vanquis.svg"),
    aliases: ["vq"],
  },
  {
    id: "vida",
    name: "Vida",
    iconFile: require("@/assets/images/bank-icons/vida.svg"),
    aliases: [],
  },
  {
    id: "virgin",
    name: "Virgin",
    iconFile: require("@/assets/images/bank-icons/virgin.svg"),
    aliases: ["vm"],
  },
  {
    id: "wealthify",
    name: "Wealthify",
    iconFile: require("@/assets/images/bank-icons/wealthify.svg"),
    aliases: [],
  },
  {
    id: "wealthtime",
    name: "Wealthtime",
    iconFile: require("@/assets/images/bank-icons/wealthtime.svg"),
    aliases: [],
  },
  {
    id: "xtb",
    name: "XTB",
    iconFile: require("@/assets/images/bank-icons/xtb.svg"),
    aliases: ["x trade brokers", "x-trade"],
  },
  {
    id: "zenith",
    name: "Zenith",
    iconFile: require("@/assets/images/bank-icons/zenith.svg"),
    aliases: [],
  },
  {
    id: "zopa",
    name: "Zopa",
    iconFile: require("@/assets/images/bank-icons/zopa.svg"),
    aliases: [],
  },
] as const;

export const banksDropdown: RichDropdownValues<BankValues> = banks.map(x => ({
  label: x.name,
  value: x.id,
  image: x.iconFile,
  aliases: x.aliases,
}))

export default banks;
