name: Update bank icons

on:
  push:
    branches:
    - main
    paths:
    - assets/images/bank-icons/**
    - .github/workflows/sync_bank_icons.yml

permissions:
  contents: read

jobs:
  sync_bank_icons_to_scaleway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Sync to Scaleway
        run: |
          aws s3 sync ./assets/images/bank-icons s3://isa-eye-assets/default-bank-icons --delete --endpoint-url https://s3.fr-par.scw.cloud
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
          AWS_DEFAULT_REGION: fr-par-1